// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ6_CUWAQHzB52C1dz6sXDR6VI-nNpNTY',
    appId: '1:460775818984:web:ac02182d377dab0cc06b5d',
    messagingSenderId: '460775818984',
    projectId: 'especies-gto',
    authDomain: 'especies-gto.firebaseapp.com',
    storageBucket: 'especies-gto.firebasestorage.app',
    measurementId: 'G-HVNRLLEDKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-v2TyoqKavdh8FfuWotyyG76bCb-awAw',
    appId: '1:460775818984:android:41fe782dd6f1cdf2c06b5d',
    messagingSenderId: '460775818984',
    projectId: 'especies-gto',
    storageBucket: 'especies-gto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALOF_0UBehIypTou5BoKJcRINr6pkXZHo',
    appId: '1:460775818984:ios:b643ab28de24f5e8c06b5d',
    messagingSenderId: '460775818984',
    projectId: 'especies-gto',
    storageBucket: 'especies-gto.firebasestorage.app',
    iosBundleId: 'com.example.especiesGuanajuato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALOF_0UBehIypTou5BoKJcRINr6pkXZHo',
    appId: '1:460775818984:ios:b643ab28de24f5e8c06b5d',
    messagingSenderId: '460775818984',
    projectId: 'especies-gto',
    storageBucket: 'especies-gto.firebasestorage.app',
    iosBundleId: 'com.example.especiesGuanajuato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ6_CUWAQHzB52C1dz6sXDR6VI-nNpNTY',
    appId: '1:460775818984:web:0cc028155cc98515c06b5d',
    messagingSenderId: '460775818984',
    projectId: 'especies-gto',
    authDomain: 'especies-gto.firebaseapp.com',
    storageBucket: 'especies-gto.firebasestorage.app',
    measurementId: 'G-KHJHD45B32',
  );
}
